### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by YuliiaHavrylenko** [dominiksalvet/asus-fan-control#75] opened 2020-12-19 13:09 UTC
When I try to install, i get problem:
sudo gitpack install github.com/dominiksalvet/asus-fan-control
E: Sub-process /usr/bin/dpkg returned an error code (1)
precp script failed with 100
<ERROR> install github.com/dominiksalvet/asus-fan-control

**Comment by dominiksalvet** [comment] 2020-12-19 23:13
Duplicate of #53

**Closed by dominiksalvet** 2020-12-19 23:13 UTC
Labels: bug
