### ISSUE TITLE
Add support for ASUS FX553VD

### ISSUE THREAD

**Issue by Greifent** [dominiksalvet/asus-fan-control#23] opened 2020-03-07 16:51 UTC
**Environment**
Latest version 3.3.0 
System: Pop_OS! 19.10 

**Basic configuration**
If only temperatures were configured, add output of:
* `sudo asus-fan-control get-temps`
```
45 50 55 60 65 70 75 80
```
* `sudo asus-fan-control model-info`
```
name GL553VD
address 1335
temperatures 65 70 72 75 78 82 86 90
tested true
```

**Additional context**
It says GL553VD, which is supported, but on the back of the computer is written FX553VD, it is a single fan and i notice that even at 80+ degree it isn't as fast and loud as windows (the maximum fan speed should be more or less 6000 rpm)

**Comment by dominiksalvet** [comment] 2020-03-07 23:03
Hello @Greifent and welcome to the asus-fan-control community! :rocket: 

Thank you so much for your intention to add a new notebook model. :heart: I must admit, however, that I have never seen something similar. I mean that you basically have a different model from GL553VD and yet you have the same model reported in the `dmidecode` output... That's strange. :thinking:

**First**, please, add the whole output of `sudo dmidecode`.

**Second**, does asus-fan-control even work on your device as per its current state? Did you notice any difference once you installed asus-fan-control or after reboot? Or are you able to notice a difference once you use custom temperatures in `sudo asus-fan-control set-temps <temps>`?

**Third**, about the maximum fan speed... I suspect that it may be caused by the fact that your model have more or less temperature values than other models. Just a thought... For these cases, I have created [afc-scout](https://github.com/dominiksalvet/afc-scout), which may help you to find out whether it is true. I would certainly give it a shot... :mag:

> Still, if it is true, it would probably mean that GL553VD model have the same issues as it looks that there are a lot of similarities between those two models (at least internally).

Should you have any issues, feel free to let me know!

Looking forward to hearing from you! :smile:

**Comment by dominiksalvet** [comment] 2020-03-07 23:05
@Greifent BTW, I have improved the format of your first post. Hope you don't mind! :smile:

**Comment by Greifent** [comment] 2020-03-07 23:08
I'll try tomorrow or Monday, BTW they are very similar, for what I read the only difference is the rgb keyboard and the ROG symbol

**Comment by dominiksalvet** [comment] 2020-03-07 23:12
> the only difference is the rgb keyboard and the ROG symbol

Based on my little search, I have thought something similar... :smile:

**Comment by Greifent** [comment] 2020-03-08 16:21
Hi
sudo dmidecode = https://pastebin.com/GpnxVqBf
I didn't notice a lot of difference, it is almost the same.
For the afc-scout you need a specific address range or not?

**Comment by dominiksalvet** [comment] 2020-03-09 18:13
@Greifent Well, that does not look well to be honest if asus-fan-control does not affect your device.

You should try to inspect values around the default address range, which is from 1335 to 1342 including the corner values. But if it was here on your device, asus-fan-control would have affected your device when run...

Still, there is a problem with your model name reported from dmidecode. If you would be able to find the base ACPI fan address for your device and the number of temperatures and it would be different from real GL553VD, I do not know how to store it to the asus-fan-control [models database](https://github.com/dominiksalvet/asus-fan-control/blob/master/data/models) not to collide with the GL553VD model...

The fact that dmidecode reports the same model name for your device and the GL553VD model, is very strange in the first place... :thinking:

**Comment by Greifent** [comment] 2020-03-09 19:46
![Screenshot from 2020-03-09 20-41-48](https://user-images.githubusercontent.com/59480824/76250933-78138780-6246-11ea-81d7-722e63b4cc40.png)

These are the value between 1334 1343

**Comment by dominiksalvet** [comment] 2020-03-09 20:31
@Greifent These values are most likely the result of asus-fan-control calling (after installation/at boot). Please, uninstall asus-fan-control using `sudo gitpack uninstall <url>` and reboot your system. Then load acpi_call module manually in case it is not loaded - `sudo modprobe acpi_call`. Now you should be able to read real unmodified ACPI values with afc-scout... :ok_hand:

**Comment by Greifent** [comment] 2020-03-09 20:36
![Screenshot from 2020-03-09 21-35-37](https://user-images.githubusercontent.com/59480824/76255147-fa537a00-624d-11ea-9c8a-90741a983169.png)

**Comment by dominiksalvet** [comment] 2020-03-09 22:21
Well, that's a good sign. I suggest using some crazy configurations that you hardly be able not to notice... E.g., `sudo asus-fan-control set-temps 20 25 30 35 40 45 50 55` or `sudo asus-fan-control set-temps 60 65 70 75 80 85 90 95`. You should be able to see the difference for these configurations, are you?

**Comment by Greifent** [comment] 2020-03-09 22:30
I'll let you know tomorrow

**Comment by Greifent** [comment] 2020-03-10 09:21
No, i cannot hear any difference, the fan speed is the same (The GPU is at 65°C)

**Comment by dominiksalvet** [comment] 2020-03-10 10:29
Well, then I really do not know how to help you. Sorry. :disappointed: 

You could possibly try to find a similar pattern using afc-scout, but the problem with ambiguous model name obtained from dmidecode will persist. It would work at least for you in case you modify asus-fan-control appropriately and will not update it.

**Comment by Greifent** [comment] 2020-03-10 10:31
So i have to change the file, remove the GL, add mine and change the value using the last photo?

**Comment by dominiksalvet** [comment] 2020-03-10 11:52
Well, it is a bit complicated in this case. But maybe you said it right.

You need to remove the GL model line from the */usr/share/asus-fan-control/models* file. Then, you need to find your address (and the number of temperatures) using the combination of afc-scout and the approach described in the [*contributing.md*](https://github.com/dominiksalvet/asus-fan-control/blob/master/contributing.md) file in the Advanced configuration.

Once you find the address, you can add the GL model line back with the new address and temperatures. Then you can use asus-fan-control as usual except for updating it.

Please, make sure that you will report the result of your investigation to us! It may help other users as well. :rocket: 

Thank you so much for your interest! :heart:

**Comment by Greifent** [comment] 2020-03-10 11:56
Ok, I'll let you know. Thanks

**Comment by Greifent** [comment] 2020-03-10 13:55
I need to remove the whole line or only the part after |1335| ?
Those value that i send before were the temperature or the ACPI address?
In this command:
sudo FALLBACK_ADDR=<addr> FALLBACK_TEMPS='<temps>' asus-fan-control set-temps default
I have to put on <addr> the ACPI address, and in the <temps> what i have to put?
Thank you

**Comment by dominiksalvet** [comment] 2020-03-10 17:32
Never ever remove only a part of the line even though asus-fan-control checks should catch it... xD You need to remove the whole line. Or there is a little trick... modify the "GL553VD" part to e.g. "GGL553VD" and your model will not be detected... once you are done, you can easily revert it back.

1335, 1336, etc. were addresses, 45, 50, 55, etc. were temperatures... :smile: Everything is in decimal form.

`<addr>` = address, e.g., `FALLBACK_ADDR=1335`
`<temps>` = temperatures, e.g., `FALLBACK_TEMPS='55 60 62 65 68 72 76 80'` (do not forget to use apostrophes (\'), they are important here)

> Those are values I would use in your case but with my device (UX430UA).

Does it make sense now? :smile_cat: 

---

Please format your code with backticks (\`) in the future. I do not want to edit your posts. Thank you! :heart:

**Comment by Greifent** [comment] 2020-03-10 17:35
Ok I will use ` sorry for that.

**Comment by Greifent** [comment] 2020-03-10 17:42
![Screenshot from 2020-03-10 18-42-13](https://user-images.githubusercontent.com/59480824/76342444-e4ea5880-62fe-11ea-9813-016981572460.png)
So like this?

**Comment by dominiksalvet** [comment] 2020-03-10 18:49
Ok, enough. :sweat: Please, read the whole issue again as well as the [contributing.md](https://github.com/dominiksalvet/asus-fan-control/blob/master/contributing.md) file, Advanced configuration. Then, ask what you do not understand to. :thinking: 

I am sorry but I think that there is more than enough information for your questions...

---

In short (if it helps):

* asus-fan-control uses dmidecode to identify devices
* your device is identified as GL553VD
* device is identified if it is in the *models* file
* if device is not identified, it will use fallback values
* you can modify fallback values with the `FALLBACK_*` variables
* `sudo asus-fan-control model-info` is very useful

**Comment by Greifent** [comment] 2020-03-10 18:52
Ok

**Comment by Greifent** [comment] 2020-03-10 19:32
Sorry but I'm not an expert on this things.
I've `sudo asus-fan-control get-temps` at `60 65 70 72 75 80 82 85`
With `sudo asus-fan-control model-info` I have 
`name GL553VD`
`address 1335`
`temperatures 65 70 72 75 78 82 86 90`
`tested true`
I can hear the fan speed change, but I still have overheating problem, it easily reach 94 degree under non heavy games (Euro Truck Simulator 2 Max, usually 60+ FPS, after 1 or 2 minutes <30 with drop under 20).

**Comment by dominiksalvet** [comment] 2020-03-10 19:53
Well, I would apply warranty repair in such case. If your device is not covered anymore, I would replace thermal compound of CPU and GPU yourself, or any PC servis will do it for you... That might help... :smile:

**Comment by Greifent** [comment] 2020-03-10 19:59
I have a partition with windows installed and on the same preset for the game I have no problem always over 60, even after hours of playing

**Comment by dominiksalvet** [comment] 2020-03-10 21:32
I do not know then... what is your progress with asus-fan-control anyways? :smiley:

**Comment by Greifent** [comment] 2020-03-10 21:36
It is better than the beginning, after lowering the temperatures. The speed change, it still doesn't reach 100% i think it is around 60/70. I set the fallback values beginning from 60 degree

**Comment by dominiksalvet** [comment] 2020-03-10 22:51
So asus-fan-control actually controls your device, right? I am really confused at this point. Until now I have though that it does not work for you at all... :smile:

**Comment by Greifent** [comment] 2020-03-10 23:00
It seems like that it is doing something, the fan kinda worked before the installation, now it is better, so I assume that it is working. Sorry for the confusion, I was also trying to figure out if it was working.

**Comment by dominiksalvet** [comment] 2020-03-11 07:49
All right. If you have any news, please let us know! 😉

**Comment by dominiksalvet** [comment] 2020-03-11 07:58
BTW try `sudo asus-fan-control set-temps 20 25 30 35 40 45 50 55` and reboot your device. Is your fan driven way more aggressively after reboot? 😃 Also take a look at `sudo asus-fan-control get-temps` output  after the reboot.

**Comment by Greifent** [comment] 2020-03-11 08:54
The fan is more aggressive; `sudo asus-fan-control get-temps` give 
`20 25 30 35 40 45 50 55`

**Comment by dominiksalvet** [comment] 2020-03-11 22:53
Well... feel free to play around with asus-fan-control for a moment and then let me know how it was going as well as your best temperature configuration if any... :smile: :rocket:

**Comment by dominiksalvet** [comment] 2020-03-12 10:33
BTW, there is still hope for adding support for your device officially. Once you have a very similar temperature configuration to the GL553VD device, which is '65 70 72 75 78 82 86 90', it would be possible to add it...

**Comment by Greifent** [comment] 2020-03-12 10:37
I'll try some configuration in the next days and let you know, I think that I would lower down the maximum temperature, maybe around 80-85 so it won't heat up that fast.

**Comment by dominiksalvet** [comment] 2020-03-12 10:48
@Greifent Yeah! :+1: Maybe @infinito84 (I hope he has the same nickname as on GitLab), the original author of GL553VD testing, can add something into this issue and we can find the best temperature configuration for both devices since they share the same model name in the dmicode output... That would be great! :rocket: 

---

BTW, keep in mind that you can get the current temperatures only using `sudo asus-fan-control get-temps`. The temperatures present in the `sudo asus-fan-control model-info` output are default ones and they are used in case of `sudo asus-fan-control set-temps default` or in case no previous temperatures has been set with `sudo asus-fan-control set-temps <temps>` (e.g., after installation)... Just for your information...

**Comment by Greifent** [comment] 2020-03-12 10:51
Thank you, I'll keep that in mind

**Comment by Greifent** [comment] 2020-03-24 19:35
Hi i've tried some temperature, the best that i found is `55 60 62 65 68 72 76 80`

**Comment by dominiksalvet** [comment] 2020-03-24 20:18
Hello and thank you for the report! :heart:

:thinking: ... those are quite different from the GL553VD ones - `65 70 72 75 78 82 86 90`. But well, I can increase your temperatures by 5 and decrease the GL553VD ones by the same amount and I will obtain the same temperatures, which I could add to asus-fan-control and declare your model to be tested... What do you think? :smile: :rocket: 

> You will still be able to set your custom temperatures, only the default ones for both your, FX553VD, and GL553VD models will be `60 65 67 70 73 77 81 85`.

**Comment by arruor** [comment] 2020-03-24 21:18
Hello @dominiksalvet @Greifent ,
the misleading model name is more likely to be related to BIOS version, as shown in the provided `dmidecode` output:

```
BIOS Information
    Vendor: American Megatrends Inc.
    Version: GL553VD.308
    Release Date: 04/29/2019
```

**Comment by Greifent** [comment] 2020-03-24 21:22
It may be, what was the version tested?

**Comment by arruor** [comment] 2020-03-24 21:31
I don't know, you have to tell ;)
I have just tried to explain why your model appears as GL553VD judging by the output of `dmidecode`.

Cheers

**Comment by Greifent** [comment] 2020-03-24 21:38
I gave a quick look and in the asus site, looking for FX553VD and driver, the BIOS is GL553VD BIOS 308, which is the one that is installed, so I think that there isn't that difference between the two models

**Comment by arruor** [comment] 2020-03-24 21:46
Yes, you're correct. For sure the motherboards and the i2c instrumentation are same as almost all the other equipment. Also GL553VD is just a ROG branded FX553VD ;)

**Comment by Greifent** [comment] 2020-03-24 21:50
You haven't got temperature problems during your testing phase?

**Comment by arruor** [comment] 2020-03-25 07:53
Yes, I haven't after installing `asus-fan-control`. Before that it was running constantly on 4200 RPM.
I found my fan became more responsive now.

Here are some brief examples:
```
root@hive:~# sensors
asus-isa-0000
Adapter: ISA adapter
cpu_fan:     3600 RPM

pch_skylake-virtual-0
Adapter: Virtual device
temp1:        +47.5°C

BAT0-acpi-0
Adapter: ACPI interface
in0:          16.23 V
curr1:         0.00 A

iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +49.0°C

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +71.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +52.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +71.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +53.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +51.0°C  (high = +100.0°C, crit = +100.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +54.0°C  (crit = +98.0°C)
```
vs
```
root@hive:~# sensors
asus-isa-0000
Adapter: ISA adapter
cpu_fan:     4700 RPM

pch_skylake-virtual-0
Adapter: Virtual device
temp1:        +49.5°C  

BAT0-acpi-0
Adapter: ACPI interface
in0:          16.23 V  
curr1:         0.00 A  

iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +46.0°C  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +72.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +72.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +69.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +60.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +62.0°C  (high = +100.0°C, crit = +100.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +71.0°C  (crit = +98.0°C)
```

**Comment by Greifent** [comment] 2020-03-25 08:01
Oh, there is my `sensor` output
`iwlwifi-virtual-0`
`Adapter: Virtual device`
`temp1:        +46.0°C`

`pch_skylake-virtual-0`
`Adapter: Virtual device`
`temp1:        +53.5°C `

`BAT0-acpi-0`
`Adapter: ACPI interface`
`in0:         +14.21 V`
`curr1:        +2.13 A`  

`asus-isa-0000`
`Adapter: ISA adapter`
`cpu_fan:        0 RPM`

`coretemp-isa-0000`
`Adapter: ISA adapter`
`Package id 0:  +61.0°C  (high = +100.0°C, crit = +100.0°C)`
`Core 0:        +58.0°C  (high = +100.0°C, crit = +100.0°C)`
`Core 1:        +59.0°C  (high = +100.0°C, crit = +100.0°C)`
`Core 2:        +57.0°C  (high = +100.0°C, crit = +100.0°C)`
`Core 3:        +59.0°C  (high = +100.0°C, crit = +100.0°C)`

`acpitz-acpi-0`
`Adapter: ACPI interface`
`temp1:   +61.0°C  (crit = +98.0°C)`
Then i don't know why i have 0 RPM

**Comment by arruor** [comment] 2020-03-25 08:47
Did you ran `sensors-detect` after installing `lm-sensors`. If you're not - please run it and answer Yes to all questions. 
If you don't have `lm-sensors` installed then run `sudo apt install lm-sensors`.  After running `sensors-detect`  and adding necessary modules to `/etc/modules` do not forget to run `/etc/init.d/kmod start` otherwise you have to restart your computer.

Also, you could check if the driver is loaded by
```
wget https://raw.githubusercontent.com/lm-sensors/lm-sensors/master/prog/debug/find-driver -O /tmp/find-driver && chmod u+x /tmp/find-driver && /tmp/find-driver asus-isa-0000
```
It should give you the following result:
```
Driver: asus-nb-wmi
Module: asus_wmi
```

**Comment by Greifent** [comment] 2020-03-25 08:54
Ok, the new output is 
`iwlwifi-virtual-0`
`Adapter: Virtual device`
`temp1:        +60.0°C  `

`pch_skylake-virtual-0`
`Adapter: Virtual device`
`temp1:        +56.0°C  `

`BAT0-acpi-0`
`Adapter: ACPI interface`
`in0:         +16.29 V  `
`curr1:        +0.77 A  `

`asus-isa-0000`
`Adapter: ISA adapter`
`cpu_fan:        0 RPM`

`coretemp-isa-0000`
`Adapter: ISA adapter`
`Package id 0:  +68.0°C  (high = +100.0°C, crit = +100.0°C)`
`Core 0:        +65.0°C  (high = +100.0°C, crit = +100.0°C)`
`Core 1:        +67.0°C  (high = +100.0°C, crit = +100.0°C)`
`Core 2:        +64.0°C  (high = +100.0°C, crit = +100.0°C)`
`Core 3:        +65.0°C  (high = +100.0°C, crit = +100.0°C)`

`acpitz-acpi-0`
`Adapter: ACPI interface`
`temp1:        +70.0°C  (crit = +98.0°C)`

And the result of `wget https://raw.githubusercontent.com/lm-sensors/lm-sensors/master/prog/debug/find-driver -O /tmp/find-driver && chmod u+x /tmp/find-driver && /tmp/find-driver asus-isa-0000`
Is what you said

**Comment by arruor** [comment] 2020-03-25 10:04
Do you have `coretemp` module loaded?
```
lsmod | grep coretemp
fgrep /etc/modules
```
If they are loaded, then try to run `sensors-detect` again.
If there is still no RPM in `sensors` - I am running out of ideas.

**Comment by Greifent** [comment] 2020-03-25 10:11
The `lsmod | grep coretemp` output is 
`coretemp               20480  0`
The `fgrep /etc/modules` took a lot to run, after two minutes it is still running

**Comment by arruor** [comment] 2020-03-25 13:28
Ah, apologies I just gave you a wrong command.
You could stop it, as it should be `fgrep coretemp /etc/modules` .
Anyway, it seems that you have necessary module loaded.
My last guest would be to run `sensors-detect` answering yes to all questions and following the instructions at the end.

Cheers,

**Comment by Greifent** [comment] 2020-03-25 13:34
That give `coretemp` written 4 times.
Retried the `sensors-detect` but still the same

**Comment by arruor** [comment] 2020-03-25 13:44
Sorry,
but I am running out of ideas :(

**Comment by dominiksalvet** [comment] 2020-03-25 18:32
Hello guys! I would like to contribute to the discussion... :smile: My `sudo sensors` output is:

```
iwlwifi-virtual-0
Adapter: Virtual device
temp1:        +41.0°C  

acpitz-virtual-0
Adapter: Virtual device
temp1:        +46.0°C  (crit = +103.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +47.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +45.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +47.0°C  (high = +100.0°C, crit = +100.0°C)

pch_skylake-virtual-0
Adapter: Virtual device
temp1:        +41.5°C
```

As you can see, I am missing some records entirely. In the `BAT0-acpi-0` case it may be causes by replacing battery for an unofficial one. About the `asus-isa-0000` and the whole RPM thing, as far as I remember correctly I have never been able to somehow detect the RPM of my laptop's fan... :disappointed: So @Greifent, maybe that's not any kind of your problem and you probably can't do anything with it... Maybe - I do not know.

---

BTW guys, `fgrep /etc/modules` command was not running, it was waiting for a user input to be processed and matched against the expression of `/etc/modules` for each line. Try yourself to run it and write `hello/etc/modules/bye` and press enter. Once you will have seen enough, press ctrl+d to send EOF. BTW, if you use `fgrep coretemp /etc/modules`, then it matches each line of */etc/modules* file agains the `coretemp` expression.

---

@Greifent I appreciate that you use the backtick (\`) for code/terminal sections but please use triple-backticks (\`\`\`) for multiple lines of code/terminal. I have already edited your previous posts, but please keep that in mind for future comments. E.g.:

> Here is my \`gitpack list\` output:
>
> \`\`\`
> github.com/dominiksalvet/vhdldep 2.1.3
> github.com/dominiksalvet/pathfinding-robots 1.0.0
> \`\`\`

Thank you so much! :heart: :rocket:

**Comment by dominiksalvet** [comment] 2020-03-25 18:33
> Hello and thank you for the report! 
> 
>  ... those are quite different from the GL553VD ones - `65 70 72 75 78 82 86 90`. But well, I can increase your temperatures by 5 and decrease the GL553VD ones by the same amount and I will obtain the same temperatures, which I could add to asus-fan-control and declare your model to be tested... What do you think?  
> 
> > You will still be able to set your custom temperatures, only the default ones for both your, FX553VD, and GL553VD models will be `60 65 67 70 73 77 81 85`.

BTW... @Greifent what do you think about my proposal mentioned in an earlier post? :thinking:

**Comment by Greifent** [comment] 2020-03-25 18:53
Sorry but i didn't know how to do multiple line, thanks. Sorry but i didn't saw your post, anyway that could work.

**Comment by dominiksalvet** [comment] 2020-03-25 19:48
All right, @Greifent your model has been officially added to asus-fan-control as a tested model in the latest release [3.5.0](https://github.com/dominiksalvet/asus-fan-control/releases/tag/3.5.0). Feel free to use GitPack to update asus-fan-control as stated below:

```
sudo gitpack install github.com/dominiksalvet/asus-fan-control
```

@Greifent **Thank you so much** for your patience and this contribution! :heart: Asus-fan-control now supports 12 different devices! :rocket: That is just incredible!! :tada: 

---

I am closing this issue as it has been resolved but you guys feel free to continue in any further discussion if you want.

**Closed by dominiksalvet** 2020-03-25 19:48 UTC
Labels: add new device

**Comment by Greifent** [comment] 2020-03-25 19:54
Ok, thanks for your time and help

**Comment by Leopard1907** [comment] 2020-04-25 12:47
Sorry about reviving an old issue report but i have the same laptop and my temps are usually at 85-86 C at full load in games like Witcher 3 etc. Usually at 4900 rpm or so. 

Is the default ( current ) temps and fan speeds are good enough or do i really need this for proper fan load?

**Comment by Greifent** [comment] 2020-04-25 14:41
No problem.
If you mean the default temperature of this program, those are fine.
If you mean that you really need this program, those temperature are fine, but keep in mind that with summer the PC can became hotter, and the possibility to change the temperatures could be helpful.
