### ISSUE TITLE
Windows support 

### ISSUE THREAD

**Issue by epokuser** [dominiksalvet/asus-fan-control#127] opened 2022-11-28 18:09 UTC
**Description**
windows support

**Reason**
Add windows support for controlling fan speeds in windows 
**Additional context**

**Comment by dominiksalvet** [comment] 2022-11-28 19:26
Hey @epokuser, unfortunately, this is completely out of context for AFC, which is built around Linux stuff. If someone wants to build something like this for Windows, I doubt the AFC code would be useful for them.

**Comment by dominiksalvet** [comment] 2022-11-28 19:26
Plus duplicate of #40.

**Closed by dominiksalvet** 2022-11-28 19:26 UTC
Labels: enhancement
