### ISSUE TITLE
file /proc/acpi/call does not exist

### ISSUE THREAD

**Issue by lamahechag** [dominiksalvet/asus-fan-control#60] opened 2020-08-27 14:19 UTC
**Environment**
State asus-fan-control version last, on Ubuntu 20.04
Asus model: TUF Gaming FX505DU
**Description**
When try `sudo asus-fan-control` I get `file /proc/acpi/call does not exist`

**Replication**
State steps to replicate above
**Additional context**
The installation was done using gitpack.

**Comment by dominiksalvet** [comment] 2020-08-27 15:32
Duplicate of #42, have a look at it. :slightly_smiling_face:

**Closed by dominiksalvet** 2020-08-27 15:32 UTC
Labels: bug

**Comment by dominiksalvet** [comment] 2020-12-12 10:06
Hello @lamahechag! :wave: Have you managed to overcome this issue? (sorry, I was quite busy in the past)

**Comment by dominiksalvet** [comment] 2021-02-22 19:10
bump

**Comment by dariader** [comment] 2023-05-08 14:37
Hi there! 
I've encountered the same issue. 
OS Ubuntu 22.04.1 LTS
Proc Ryzen 9 (Cezanne)


Installation
```~/Downloads/tmp/asus-fan-control$ sudo gitpack install github.com/dominiksalvet/asus-fan-control
[sudo] password for daria: 
>>> running install for github.com/dominiksalvet/asus-fan-control
local repository fresh
reading status database
using automatic candidate version
installing version 3.14.0
running script .install/install-global-Linux
installing acpi-call-dkms package
copying files
enabling systemd service
loading acpi_call module first time
modprobe: ERROR: could not insert 'acpi_call': Key was rejected by service
applying fan speed changes
file /proc/acpi/call does not exist
failed to apply changes now; reboot may help
adding to status database
<<< done; successfully installed
```
When calling AFC

```/tmp/asus-fan-control$ sudo asus-fan-control
file /proc/acpi/call does not exist
```
Rebooting the laptop have not helped. 


Any tips how to overcome?

**Comment by dominiksalvet** [comment] 2023-05-09 12:46
@dariader Hello,
1) You have an AMD processor, with which AFC does not work.
2) Maybe you have secure boot enabled, which may cause issues.
3) Kernel version may also play a role in this.

Unfortunately, I cannot help more since I am rather clueless here, I am sorry.

**Comment by Caelgoul** [comment] 2023-12-19 01:52
**Asus Zenbook 4071Q  [Manjaro plasma kde]**

```
[itdev@asus asus-fan-control]$ sudo asus-fan-control
file /proc/acpi/call does not exist
```
