### ISSUE TITLE
warning: command substitution: ignored null byte in input

### ISSUE THREAD

**Issue by lucamarini22** [dominiksalvet/asus-fan-control#77] opened 2020-12-25 09:49 UTC
Good morning,

I installed asus-fan-control on my Asus **K53SC**, my os is **arch-linux**, and when I execute sudo asus-fan-control I get these warnings:

/usr/bin/asus-fan-control: line 420: warning: command substitution: ignored null byte in input
/usr/bin/asus-fan-control: line 420: warning: command substitution: ignored null byte in input
/usr/bin/asus-fan-control: line 420: warning: command substitution: ignored null byte in input
/usr/bin/asus-fan-control: line 420: warning: command substitution: ignored null byte in input
/usr/bin/asus-fan-control: line 420: warning: command substitution: ignored null byte in input
/usr/bin/asus-fan-control: line 420: warning: command substitution: ignored null byte in input
/usr/bin/asus-fan-control: line 420: warning: command substitution: ignored null byte in input
/usr/bin/asus-fan-control: line 420: warning: command substitution: ignored null byte in input

**Comment by dominiksalvet** [comment] 2020-12-28 11:18
Hello @lucamarini22 and welcome to the asus-fan-control community! :wave: :tada:

I have already seen this issue on another Arch-based system (see #66). We haven't bothered back then but something tells me that more users might be affected and it is a shame for AFC (and [afc-scout](https://github.com/dominiksalvet/afc-scout) as well) since it should be harmless.

It would be great if you could get together with @FadeMind and prepare a patch for this warning since I cannot reproduce it myself on Ubuntu. Please keep in mind that the suspicious line 420 is on the version you have installed (probably [tag 3.9.0](https://github.com/dominiksalvet/asus-fan-control/tree/3.9.0)), not on master (it may be a different line here).

[This SO answer](https://stackoverflow.com/a/46163928) looks promising. We need to make sure, though, that `tr` works the same as `cat` in this case since [the acpi_call examples](https://github.com/mkottman/acpi_call) use `cat` (but it may work since both invoke file read).

**Comment by lucamarini22** [comment] 2020-12-28 12:12
Thank you for answering me @dominiksalvet !!

I changed the line 420 from:
`
    result="$(cat "$ACPI_CALL_PATH")" &&
`
to:
`
    result="$(tr -d '\0' < /proc/device-tree/model)" &&
`
and now it tells me this:
`
   /usr/bin/asus-fan-control: line 420: /proc/device-tree/model: No such file or directory
`

The problem is that my pwm fan sensor is not detected by the command sensors, which gives me the following output:

asus-isa-0000
Adapter: ISA adapter
temp1:        +44.0°C  

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +44.0°C  (crit = +103.0°C)

BAT0-acpi-0
Adapter: ACPI interface
in0:           4.99 V  
curr1:         0.00 A  


and the command pwmconfig gives me this:

# pwmconfig version 3.6.0
This program will search your sensors for pulse width modulation (pwm)
controls, and test each one to see if it controls a fan on
your motherboard. Note that many motherboards do not have pwm
circuitry installed, even if your sensor chip supports pwm.

We will attempt to briefly stop each fan using the pwm controls.
The program will attempt to restore each fan to full speed
after testing. However, it is ** very important ** that you
physically verify that the fans have been to full speed
after the program has completed.

/usr/bin/pwmconfig: There are no pwm-capable sensor modules installed

**Comment by dominiksalvet** [comment] 2020-12-28 12:58
> So I think that the precedent null error was due to the fact that the file does not exist.

This is not true I think. You have used a different path during your test. The SO answer was an analogy... Instead of `/proc/device-tree/model` use `"$ACPI_CALL_PATH"` and everything should be fine hopefully.

**Comment by lucamarini22** [comment] 2020-12-28 13:15
You're right, I lost that detail :)

By the way, now I don't get any warning, but by executing this:
`
sudo asus-fan-control set-temps 30 35 40 45 50 55 60 65   
`
and then this:
`
sudo asus-fan-control set-temps 60 65 70 75 80 85 90 95      
`

the fan speed does not change at all

And as I said before I can't even detect my fan in the output of the commands I wrote in the previous message

**Comment by dominiksalvet** [comment] 2020-12-28 23:41
> And as I said before I can't even detect my fan in the output of the commands I wrote in the previous message

I know, do not worry. I am trying to take my time reading all post texts but this particular information is not very useful for me. I am not an ACPI expert by any means – I only created a convenient script that either works or not. That's pretty much all... :smiley: 

> You're right, I lost that detail :)

Will you create the PR with the change applied to the master branch? (see [contributing](https://github.com/dominiksalvet/asus-fan-control/blob/master/contributing.md) for more details – you do not have to update changelog, I will help you with that if you wish)

> the fan speed does not change at all

Got it. Also try getting the set temperatures whether they are equal, which is one of the infamous AFC issues.

**Comment by lucamarini22** [comment] 2020-12-29 12:35
> Got it. Also try getting the set temperatures whether they are equal, which is one of the infamous AFC issues.

If you mean that when I set the temps and then get them, they are correct.

> Will you create the PR with the change applied to the master branch? (see contributing for more details – you do not have to update changelog, I will help you with that if you wish)

I did that now without updating the changelog, let me know

**Comment by dominiksalvet** [comment] 2020-12-29 14:56
> If you mean that when I set the temps and then get them, they are correct.

Well, maybe you can try what is suggested here https://github.com/dominiksalvet/asus-fan-control/issues/76#issuecomment-751659361 since it seems to have very similar symptoms in fan control manner.

**Comment by lucamarini22** [comment] 2020-12-31 13:05
Ok, so I followed #76 (comment) (I uninstalled asus-fan-control, reboot) and when I execute afc-scout I get this output:
```
------ base address 1335 ------
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1334] = 0
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1335] = 40 <- possible start
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1336] = 47
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1337] = 55
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1338] = 62
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1339] = 72
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1340] = 80
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1341] = 85
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1342] = 90 <- possible end
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1343] = 95
------ base address 1431 ------
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1430] = 44
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1431] = 80 <- possible start
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1432] = 84
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1433] = 89
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1434] = 94
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1435] = 94
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1436] = 94
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1437] = 94
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1438] = 94 <- possible end
/usr/local/bin/afc-scout: line 56: warning: command substitution: ignored null byte in input
[1439] = 98
```

so I changed this:
`
result="$(cat "$ACPI_CALL_PATH")" &&
`
into this:
`
result="$(tr -d '\0' < "$ACPI_CALL_PATH")" &&
`
(I will create a pull request)

and here you can find the output of `afc-scout 0 4095`:

https://github.com/lucamarini22/lucamarini22/blob/main/outoput_of_afc_scout_0_4095.txt

**Comment by dominiksalvet** [comment] 2021-01-01 11:40
> I will create a pull request. -> Edit: ok I wont' create it because it's already changed on the repository, but when I downloaded it it was not

Yeah, I was quicker! :smile: Once a new version is released, it will be part of its delivery.

> and here you can find the output of `afc-scout 0 4095`:

Did you know that you could have dragged the file into the text field and include it as an attachment instead of pushing it to your repository? :thinking: 

You know what? The core of this very issue has been already solved, so I will close this issue. Please, create a new issue for adding support for your device to keep up with the context and add all relevant information, such as `model-info`, `set-temps` and `get-temps` uses + behavior, and the afc-scout output mentioned in your post. Hope you will understand that.

**Closed by dominiksalvet** 2021-01-01 11:40 UTC
Labels: question

**Comment by dominiksalvet** [comment] 2021-01-23 17:27
Just quick info on this issue. The relevant fix is already present in master branch, yet the latest stable release does not have it. Once a new version is released, this bugfix will be part of it. The new AFC release will happen once GitPack 1.0.0 will be out. Thank you for your patience. :rocket:

**Comment by dominiksalvet** [comment] 2021-02-14 10:10
Fixed in the latest release! :rocket: :rocket:
